### ISSUE TITLE
Problem with register_widget()

### ISSUE THREAD

**Issue by aksld** [BeAPI/composer-scaffold-plugin#3]
#### Version information

* Plugin version : dev-master
* PHP : 7.2
* WordPress : 4.9.8

#### Steps to reproduce

1. `composer scaffold-plugin test`
2. Without additional components

#### What was expected

Version without register_widget().

#### What happened instead

```
// Widgets
add_action( 'widgets_init', function () {
	register_widget( '\AKSL\My_Great_Plugin\Widgets\Main' );
} );
```

Every time I create a plugin, I have to delete this code that generates an error.

P.S : Thank you for this wonderful tool 👍

**Comment by MaximeCulea** [comment]
Hello @aksld,

As it is from the skeleton, I have a good news to tell you. It has been fixed : https://github.com/BeAPI/bea-plugin-boilerplate/pull/16

Thx for you patience.
Best

**Comment by aksld** [comment]
Thanks 👍
