### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by Rahe** [BeAPI/composer-scaffold-plugin#4]
Hello,

The package bea/composer/scaffold-plugin isn't a package vendor/namespace allowed.
Composer throw errors at each composer install/update.
We need to rename it to beapi/composer-scaffold-plugin in my opinion.

We have to :

1. Make a tag if not already wit the old namespace
2. Change the vendor/package name and make a new tag

Nicolas,

**Comment by asadowski10** [comment]
okey

**Comment by Rahe** [comment]
Done in 2.0.0
